### ISSUE TITLE
Install instruction

### ISSUE THREAD

**Issue by PowerKiKi** [GeertjanWielenga/TypeScript#2]
I am not familiar with NetBeans plugin development. Would you please enlighten me and let me know how to build/install this for testing, please ?

**Comment by GeertjanWielenga** [comment]
Well, it's a Maven project. Build the project and you'll have an NBM file in the target folder, which you can install in NetBeans. Note it is very early days and there'll be bugs.

**Comment by philipg-pm** [comment]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 40.369s
[INFO] Finished at: Fri Nov 13 10:45:34 GMT 2015
[INFO] Final Memory: 7M/126M
[INFO] ------------------------------------------------------------------------
[ERROR] Unknown lifecycle phase "build". You must specify a valid lifecycle phas
e or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-ar
tifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate,
initialize, generate-sources, process-sources, generate-resources, process-resou
rces, compile, process-classes, generate-test-sources, process-test-sources, gen
erate-test-resources, process-test-resources, test-compile, process-test-classes
, test, prepare-package, package, pre-integration-test, integration-test, post-i
ntegration-test, verify, install, deploy, pre-site, site, post-site, site-deploy
, pre-clean, clean, post-clean. -> [Help 1]

I tried mvn build install

**Comment by timautin** [comment]
Hi,
I successfully built the plugin, but I can't install it, Netbeans is asking for JavaScript2 Editor :

Some plugins require plugin JavaScript2 Editor to be installed.
The plugin JavaScript2 Editor is requested in implementation version 201508041349.  The following plugin is affected:       TypeScript

I installed the latest Netbeans nightly build (201511130002), and the error still occurs. Any idea?

**Comment by GeertjanWielenga** [comment]
Here's the plugin you're looking for:

blog.everlaw.com/2015/10/06/open-source-typescript-netbeans/

Drop me a mail at geertjan.wielenga@oracle.com for further help.

**Comment by PowerKiKi** [comment]
Does this means that GeertjanWielenga/TypeScript is dead ?

**Comment by PowerKiKi** [comment]
To answer my own question, there is a discussion about that on https://github.com/Everlaw/nbts/issues/1

**Comment by GeertjanWielenga** [comment]
Yes, please stop using this plugin. I will be removing it. The other one is much better.

**Comment by timautin** [comment]
Thanks for your answers. I already tested the other plugin, which makes my Netbeans hangs every time I save a file. Seems like the plugin is trying to analyse every files of the project, even those specified in the exclude part of tsconfig.json.

**Comment by GeertjanWielenga** [comment]
Did you tell them that in their issue tracker (instead of this one)? They've been using that plugin in production for quite some time already, so this particular problem is not something they can be encountering themselves.

**Comment by timautin** [comment]
Not yet. It is probably due to my project architecture, but they do not provide a project sample. Thanks again for your support, I will ask on their issue tracker.

**Comment by PowerKiKi** [comment]
Use https://github.com/Everlaw/nbts for a while now
